# -*- coding: utf-8 -*-
"""SpotifyProject

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13PIy7v5jDAbSDvWs1XxtEISRX6sbfeUq
"""

import pandas as pd # data analysis 
from google.colab import files # import files 
uploaded = files.upload()

mus = pd.read_csv('top2018.csv') # read data set

mus # print data set

mus[:10] # first 10 (top 10 songs)

import matplotlib.pyplot as plt # data visualization
plt.style.use('fivethirtyeight') # style of graph

top10 = mus[:10] # create data set of top 10 songs 
top10

top90 = mus[10:100] # create data set of top 11-100 songs 
top90

plt.figure(figsize=(20,7)) # plot figure size 
plt.title('Danceability vs Energy (Top 10 Songs of 2018)') # plot tile 
plt.plot(top10['danceability']) # plot danceability 
plt.plot(top10['energy']) # plot energy 
plt.xlabel('Songs (0-9)') # plot x label 
plt.ylabel('Rate (0-1)') # plot y label 
plt.legend('upper-left') # plot legend 
plt.show() # plot graph

plt.figure(figsize=(20,7)) # plot figure size 
plt.title('Danceability vs Energy (Top 90 Songs of 2018)') # plot title 
plt.plot(top90['danceability']) # danceability 
plt.plot(top90['energy']) # energy 
plt.xlabel('Songs (0-9)') # x label 
plt.ylabel('Rate (0-1)') # y label 
plt.legend('upper-left') # plot legend 
plt.show() # plot the graph

print(top10['danceability'].mean()) # mean danceability of top 10 songs 
print(top10['energy'].mean()) # mean energy of top 10 songs 
print(top10['loudness'].mean()) # mean loudness of top 10 songs 
print(top10['liveness'].mean()) # mean liveness of top 10 songs 
print(top10['tempo'].mean()) # mean tempo of top 10 songs

print(top90['danceability'].mean()) # mean danceability of top 11-100 songs 
print(top90['energy'].mean()) # mean energy of top 11-100 songs 
print(top90['loudness'].mean()) # mean loudness of top 11-100 songs 
print(top90['liveness'].mean()) # mean liveness of top 11-100 songs 
print(top90['tempo'].mean()) # mean tempo of top 11-100 songs

# compare the top 10 songs to the rest of the songs in the top 100 
difference_in_dance = (top90['danceability'].mean()) - (top10['danceability'].mean()) # difference in dance 
print(difference_in_dance)
difference_in_energy = (top90['energy'].mean()) - (top10['energy'].mean()) # difference in energy 
print(difference_in_energy)
difference_in_loudness = (top90['loudness'].mean()) - (top10['loudness'].mean()) # difference in loudness
print(difference_in_loudness)
difference_in_liveness = (top90['liveness'].mean()) - (top10['liveness'].mean()) # difference in liveness 
print(difference_in_liveness)
difference_in_tempo = (top90['tempo'].mean()) - (top10['tempo'].mean()) # difference in tempo 
print(difference_in_tempo)

if top90['danceability'].mean() > top10['danceability'].mean():
  print('Top 10-100 songs have more danceability than the top 10 songs of 2018 based on the mean of the sample.')
else: 
  print('Top 10-100 songs have less danceability than the top 10 songs of 2018 based on the mean of the sample.')

if top90['energy'].mean() > top10['energy'].mean():
  print('Top 10-100 songs have more energy.')
else:
  print('Top 10-100 songs have less energy')

plt.title('Loudness vs Energy (Top 10-100 Songs')
plt.figure(figsize=(20,7)) # plot figure size 
plt.plot(top90['loudness']) # plot loudness of top 11-100 songs 
plt.plot(top90['energy']) # plot energy of top 11-100 songs 
plt.xlabel('Songs') # plot x label 
plt.ylabel('Rating') # plot y label 
plt.show() # show the graph

top90['artists'] # print the top 10-100 artists

print(top90['acousticness'].mean()) # find the mean of the acousticness then see which one has a more acousticness 
print(top10['acousticness'].mean())

top10['energy'].mode() # the mode of the energy is higher in the top 90 (10-100 songs) compared to the energy in the top 10 songs 
top90['energy'].mode()

top10['artists'].mode()
top90['artists'].mode()

top90['artists'].mode()

top10['artists'].mode()